// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbELUyO2msBkxZPJjT0rXLXfaZnlPpUmk',
    appId: '1:245813799404:web:aa0567098ea31495f0f8c9',
    messagingSenderId: '245813799404',
    projectId: 'temoo-ae42b',
    authDomain: 'temoo-ae42b.firebaseapp.com',
    storageBucket: 'temoo-ae42b.firebasestorage.app',
    measurementId: 'G-NYFJYNFP0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFDhYoFR5UIV_9GtbV_HtUgsM4FVug25g',
    appId: '1:245813799404:android:a783c6eaeb1f14e5f0f8c9',
    messagingSenderId: '245813799404',
    projectId: 'temoo-ae42b',
    storageBucket: 'temoo-ae42b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZceYHqasEXgu5gmnIaCD2K2verutZDA',
    appId: '1:245813799404:ios:57821d6d53150e76f0f8c9',
    messagingSenderId: '245813799404',
    projectId: 'temoo-ae42b',
    storageBucket: 'temoo-ae42b.firebasestorage.app',
    iosBundleId: 'com.example.tereMood',
  );
}
